// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANPUVrA05vXp7mChoTyfD7TbPEdQ29YV8',
    appId: '1:79588606825:web:69076db42e3d083c5073f8',
    messagingSenderId: '79588606825',
    projectId: 'primal-abacus-314913',
    authDomain: 'primal-abacus-314913.firebaseapp.com',
    databaseURL: 'https://primal-abacus-314913-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'primal-abacus-314913.appspot.com',
    measurementId: 'G-FX0S1RD4G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvD9rtrabCcyIJEopRHAXJF6JMSxXu_gY',
    appId: '1:79588606825:android:87b5fd458d689fe85073f8',
    messagingSenderId: '79588606825',
    projectId: 'primal-abacus-314913',
    databaseURL: 'https://primal-abacus-314913-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'primal-abacus-314913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-IcTW2MRrKHbH90-vGw89XlXkww0n-Ls',
    appId: '1:79588606825:ios:42accf1b44474cde5073f8',
    messagingSenderId: '79588606825',
    projectId: 'primal-abacus-314913',
    databaseURL: 'https://primal-abacus-314913-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'primal-abacus-314913.appspot.com',
    iosBundleId: 'com.example.lab10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-IcTW2MRrKHbH90-vGw89XlXkww0n-Ls',
    appId: '1:79588606825:ios:5f61581bf238d4d45073f8',
    messagingSenderId: '79588606825',
    projectId: 'primal-abacus-314913',
    databaseURL: 'https://primal-abacus-314913-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'primal-abacus-314913.appspot.com',
    iosBundleId: 'com.example.lab10.RunnerTests',
  );
}
